name: Deployment

on:
  push:
    branches: [main] # master 分支有 push 时触发
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 下载源码
      # 这一步就是检出你的仓库并下载里面的代码到runner中
      - name: Checkout
        uses: actions/checkout@v3

      # 打包构建
      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: "16.x"
      - run: npm install # 安装依赖
      - run: npm run docs:build # 打包

      # 部署到 GitHub pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # 使用部署到 GitHub pages 的 action
        with:
          publish_dir: ./docs/.vitepress/dist/ # 部署打包后的 dist 目录
          github_token: ${{ secrets.DESIGN_SECRET }} # secret 名
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: 自动部署流水线：https://github.com/webtj/missyt-utils # 部署时的 git 提交信息，自由填写
